"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2023 Yunseong Hwang

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ContextType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ContextTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ContextType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DEFAULT: _ContextType.ValueType  # 0
    EVENT: _ContextType.ValueType  # 1

class ContextType(_ContextType, metaclass=_ContextTypeEnumTypeWrapper): ...

DEFAULT: ContextType.ValueType  # 0
EVENT: ContextType.ValueType  # 1
global___ContextType = ContextType

@typing.final
class ContextInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    id: builtins.str
    instance: builtins.str
    index: builtins.int
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        instance: builtins.str = ...,
        index: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "index", b"index", "instance", b"instance"]) -> None: ...

global___ContextInfo = ContextInfo

@typing.final
class Context(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_TYPE_FIELD_NUMBER: builtins.int
    CONTEXT_INFO_FIELD_NUMBER: builtins.int
    context_type: global___ContextType.ValueType
    @property
    def context_info(self) -> global___ContextInfo: ...
    def __init__(
        self,
        *,
        context_type: global___ContextType.ValueType = ...,
        context_info: global___ContextInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context_info", b"context_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context_info", b"context_info", "context_type", b"context_type"]) -> None: ...

global___Context = Context

@typing.final
class CreateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    CLSID_FIELD_NUMBER: builtins.int
    clsid: builtins.str
    @property
    def context(self) -> global___Context: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
        clsid: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["clsid", b"clsid", "context", b"context"]) -> None: ...

global___CreateRequest = CreateRequest

@typing.final
class CreateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSTANCE_FIELD_NUMBER: builtins.int
    instance: builtins.str
    def __init__(
        self,
        *,
        instance: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["instance", b"instance"]) -> None: ...

global___CreateResponse = CreateResponse

@typing.final
class ReferRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    instance: builtins.str
    @property
    def context(self) -> global___Context: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
        instance: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "instance", b"instance"]) -> None: ...

global___ReferRequest = ReferRequest

@typing.final
class ReferResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESSFUL_FIELD_NUMBER: builtins.int
    successful: builtins.bool
    def __init__(
        self,
        *,
        successful: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["successful", b"successful"]) -> None: ...

global___ReferResponse = ReferResponse

@typing.final
class ReleaseRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    instance: builtins.str
    @property
    def context(self) -> global___Context: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
        instance: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "instance", b"instance"]) -> None: ...

global___ReleaseRequest = ReleaseRequest

@typing.final
class ReleaseResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESSFUL_FIELD_NUMBER: builtins.int
    successful: builtins.bool
    def __init__(
        self,
        *,
        successful: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["successful", b"successful"]) -> None: ...

global___ReleaseResponse = ReleaseResponse

@typing.final
class DestroyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    instance: builtins.str
    @property
    def context(self) -> global___Context: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
        instance: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "instance", b"instance"]) -> None: ...

global___DestroyRequest = DestroyRequest

@typing.final
class DestroyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESSFUL_FIELD_NUMBER: builtins.int
    successful: builtins.bool
    def __init__(
        self,
        *,
        successful: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["successful", b"successful"]) -> None: ...

global___DestroyResponse = DestroyResponse

@typing.final
class ListRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    @property
    def context(self) -> global___Context: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context"]) -> None: ...

global___ListRequest = ListRequest

@typing.final
class ListItem(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSTANCE_FIELD_NUMBER: builtins.int
    CLSID_FIELD_NUMBER: builtins.int
    REFERENCES_FIELD_NUMBER: builtins.int
    instance: builtins.str
    clsid: builtins.str
    references: builtins.int
    def __init__(
        self,
        *,
        instance: builtins.str = ...,
        clsid: builtins.str = ...,
        references: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["clsid", b"clsid", "instance", b"instance", "references", b"references"]) -> None: ...

global___ListItem = ListItem

@typing.final
class ListResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEMS_FIELD_NUMBER: builtins.int
    @property
    def items(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ListItem]: ...
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[global___ListItem] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

global___ListResponse = ListResponse

@typing.final
class DescribeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    instance: builtins.str
    @property
    def context(self) -> global___Context: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
        instance: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "instance", b"instance"]) -> None: ...

global___DescribeRequest = DescribeRequest

@typing.final
class PropertyInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PROPERTY_TYPE_FIELD_NUMBER: builtins.int
    IS_READABLE_FIELD_NUMBER: builtins.int
    IS_WRITABLE_FIELD_NUMBER: builtins.int
    index: builtins.int
    name: builtins.str
    property_type: builtins.str
    is_readable: builtins.bool
    is_writable: builtins.bool
    def __init__(
        self,
        *,
        index: builtins.int = ...,
        name: builtins.str = ...,
        property_type: builtins.str = ...,
        is_readable: builtins.bool = ...,
        is_writable: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["index", b"index", "is_readable", b"is_readable", "is_writable", b"is_writable", "name", b"name", "property_type", b"property_type"]) -> None: ...

global___PropertyInfo = PropertyInfo

@typing.final
class ArgumentInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    ARGUMENT_TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    argument_type: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        argument_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["argument_type", b"argument_type", "name", b"name"]) -> None: ...

global___ArgumentInfo = ArgumentInfo

@typing.final
class MethodInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    RETURN_TYPE_FIELD_NUMBER: builtins.int
    index: builtins.int
    name: builtins.str
    return_type: builtins.str
    @property
    def arguments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ArgumentInfo]: ...
    def __init__(
        self,
        *,
        index: builtins.int = ...,
        name: builtins.str = ...,
        arguments: collections.abc.Iterable[global___ArgumentInfo] | None = ...,
        return_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["arguments", b"arguments", "index", b"index", "name", b"name", "return_type", b"return_type"]) -> None: ...

global___MethodInfo = MethodInfo

@typing.final
class EventInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    index: builtins.int
    name: builtins.str
    @property
    def arguments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ArgumentInfo]: ...
    def __init__(
        self,
        *,
        index: builtins.int = ...,
        name: builtins.str = ...,
        arguments: collections.abc.Iterable[global___ArgumentInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["arguments", b"arguments", "index", b"index", "name", b"name"]) -> None: ...

global___EventInfo = EventInfo

@typing.final
class DescribeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROPERTIES_FIELD_NUMBER: builtins.int
    METHODS_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    @property
    def properties(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PropertyInfo]: ...
    @property
    def methods(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MethodInfo]: ...
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EventInfo]: ...
    def __init__(
        self,
        *,
        properties: collections.abc.Iterable[global___PropertyInfo] | None = ...,
        methods: collections.abc.Iterable[global___MethodInfo] | None = ...,
        events: collections.abc.Iterable[global___EventInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["events", b"events", "methods", b"methods", "properties", b"properties"]) -> None: ...

global___DescribeResponse = DescribeResponse

@typing.final
class VariantList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Variant]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Iterable[global___Variant] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

global___VariantList = VariantList

@typing.final
class VaraintHashMap(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ValuesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___Variant: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___Variant | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___Variant]: ...
    def __init__(
        self,
        *,
        values: collections.abc.Mapping[builtins.str, global___Variant] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

global___VaraintHashMap = VaraintHashMap

@typing.final
class Variant(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BOOL_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    INT_VALUE_FIELD_NUMBER: builtins.int
    UINT_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    LIST_VALUE_FIELD_NUMBER: builtins.int
    MAP_VALUE_FIELD_NUMBER: builtins.int
    bool_value: builtins.bool
    string_value: builtins.str
    int_value: builtins.int
    uint_value: builtins.int
    double_value: builtins.float
    @property
    def list_value(self) -> global___VariantList: ...
    @property
    def map_value(self) -> global___VaraintHashMap: ...
    def __init__(
        self,
        *,
        bool_value: builtins.bool = ...,
        string_value: builtins.str = ...,
        int_value: builtins.int = ...,
        uint_value: builtins.int = ...,
        double_value: builtins.float = ...,
        list_value: global___VariantList | None = ...,
        map_value: global___VaraintHashMap | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["bool_value", b"bool_value", "double_value", b"double_value", "int_value", b"int_value", "list_value", b"list_value", "map_value", b"map_value", "string_value", b"string_value", "uint_value", b"uint_value", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bool_value", b"bool_value", "double_value", b"double_value", "int_value", b"int_value", "list_value", b"list_value", "map_value", b"map_value", "string_value", b"string_value", "uint_value", b"uint_value", "value", b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["value", b"value"]) -> typing.Literal["bool_value", "string_value", "int_value", "uint_value", "double_value", "list_value", "map_value"] | None: ...

global___Variant = Variant

@typing.final
class GetPropertyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    instance: builtins.str
    index: builtins.int
    @property
    def context(self) -> global___Context: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
        instance: builtins.str = ...,
        index: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "index", b"index", "instance", b"instance"]) -> None: ...

global___GetPropertyRequest = GetPropertyRequest

@typing.final
class GetPropertyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> global___Variant: ...
    def __init__(
        self,
        *,
        value: global___Variant | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___GetPropertyResponse = GetPropertyResponse

@typing.final
class SetPropertyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    instance: builtins.str
    index: builtins.int
    @property
    def context(self) -> global___Context: ...
    @property
    def value(self) -> global___Variant: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
        instance: builtins.str = ...,
        index: builtins.int = ...,
        value: global___Variant | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context", "value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "index", b"index", "instance", b"instance", "value", b"value"]) -> None: ...

global___SetPropertyRequest = SetPropertyRequest

@typing.final
class SetPropertyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESSFUL_FIELD_NUMBER: builtins.int
    successful: builtins.bool
    def __init__(
        self,
        *,
        successful: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["successful", b"successful"]) -> None: ...

global___SetPropertyResponse = SetPropertyResponse

@typing.final
class InvokeMethodRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    instance: builtins.str
    index: builtins.int
    @property
    def context(self) -> global___Context: ...
    @property
    def arguments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Variant]: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
        instance: builtins.str = ...,
        index: builtins.int = ...,
        arguments: collections.abc.Iterable[global___Variant] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["arguments", b"arguments", "context", b"context", "index", b"index", "instance", b"instance"]) -> None: ...

global___InvokeMethodRequest = InvokeMethodRequest

@typing.final
class InvokeMethodResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RETURN_VALUE_FIELD_NUMBER: builtins.int
    @property
    def return_value(self) -> global___Variant: ...
    def __init__(
        self,
        *,
        return_value: global___Variant | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["return_value", b"return_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["return_value", b"return_value"]) -> None: ...

global___InvokeMethodResponse = InvokeMethodResponse

@typing.final
class ConnectEventRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    instance: builtins.str
    index: builtins.int
    @property
    def context(self) -> global___Context: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
        instance: builtins.str = ...,
        index: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "index", b"index", "instance", b"instance"]) -> None: ...

global___ConnectEventRequest = ConnectEventRequest

@typing.final
class ConnectEventResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESSFUL_FIELD_NUMBER: builtins.int
    successful: builtins.bool
    def __init__(
        self,
        *,
        successful: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["successful", b"successful"]) -> None: ...

global___ConnectEventResponse = ConnectEventResponse

@typing.final
class DisconnectEventRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTEXT_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    instance: builtins.str
    index: builtins.int
    @property
    def context(self) -> global___Context: ...
    def __init__(
        self,
        *,
        context: global___Context | None = ...,
        instance: builtins.str = ...,
        index: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["context", b"context", "index", b"index", "instance", b"instance"]) -> None: ...

global___DisconnectEventRequest = DisconnectEventRequest

@typing.final
class DisconnectEventResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESSFUL_FIELD_NUMBER: builtins.int
    successful: builtins.bool
    def __init__(
        self,
        *,
        successful: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["successful", b"successful"]) -> None: ...

global___DisconnectEventResponse = DisconnectEventResponse

@typing.final
class HandleEventRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    ARGUMENTS_FIELD_NUMBER: builtins.int
    IS_PING_FIELD_NUMBER: builtins.int
    IS_PONG_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    id: builtins.str
    instance: builtins.str
    index: builtins.int
    is_ping: builtins.bool
    is_pong: builtins.bool
    @property
    def arguments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Variant]: ...
    def __init__(
        self,
        *,
        timestamp: builtins.int = ...,
        id: builtins.str = ...,
        instance: builtins.str = ...,
        index: builtins.int = ...,
        arguments: collections.abc.Iterable[global___Variant] | None = ...,
        is_ping: builtins.bool = ...,
        is_pong: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["arguments", b"arguments", "id", b"id", "index", b"index", "instance", b"instance", "is_ping", b"is_ping", "is_pong", b"is_pong", "timestamp", b"timestamp"]) -> None: ...

global___HandleEventRequest = HandleEventRequest

@typing.final
class HandleEventResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    INSTANCE_FIELD_NUMBER: builtins.int
    INDEX_FIELD_NUMBER: builtins.int
    IS_PING_FIELD_NUMBER: builtins.int
    IS_PONG_FIELD_NUMBER: builtins.int
    id: builtins.str
    instance: builtins.str
    index: builtins.int
    is_ping: builtins.bool
    is_pong: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        instance: builtins.str = ...,
        index: builtins.int = ...,
        is_ping: builtins.bool = ...,
        is_pong: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "index", b"index", "instance", b"instance", "is_ping", b"is_ping", "is_pong", b"is_pong"]) -> None: ...

global___HandleEventResponse = HandleEventResponse
