version = 1

[[annotations]]
path = [
  "src/python/axserve/proto/*_pb2.py",
  "src/python/axserve/proto/*_pb2.pyi",
  "src/python/axserve/proto/*_pb2_grpc.py",
  "src/python/axserve/proto/*_pb2_grpc.pyi",
  "typings/**/*.pyi",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  ".clang-format",
  ".gitattributes",
  ".gitignore",
  ".gitmodules",
  ".pre-commit-config.yaml",
  "pyproject.toml",
  "CMakePresets.json"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["axserve.png"]
SPDX-FileCopyrightText = "2025 Yunseong Hwang"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["patches/zlib-ng-2.2.4.patch"]
SPDX-FileCopyrightText = "2025 Yunseong Hwang"
SPDX-License-Identifier = "Zlib"

[[annotations]]
path = ["README.md"]
SPDX-FileCopyrightText = "2025 Yunseong Hwang"
SPDX-License-Identifier = "Apache-2.0"
