from _typeshed import Incomplete

class TypelibSpec:
    clsid: Incomplete
    lcid: Incomplete
    major: Incomplete
    minor: Incomplete
    dll: Incomplete
    desc: Incomplete
    ver_desc: Incomplete
    flags: Incomplete
    def __init__(self, clsid, lcid, major, minor, flags: int = 0) -> None: ...
    def __getitem__(self, item): ...
    def __lt__(self, other): ...
    def __eq__(self, other): ...
    def Resolve(self): ...
    def FromTypelib(self, typelib, dllName=None) -> None: ...

def EnumKeys(root): ...

FLAG_RESTRICTED: int
FLAG_CONTROL: int
FLAG_HIDDEN: int

def EnumTlbs(excludeFlags: int = 0): ...
def FindTlbsWithDescription(desc): ...
def SelectTlb(title: str = "Select Library", excludeFlags: int = 0): ...
